# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dinesh Singh
tagline:          'My Profile'
url:              https://dinesh94singh.github.io/

author:
  name:           'Dinesh Singh'
  url:            https://www.linkedin.com/in/dinesh-singh-6183a162/
  gravatar_md5:   2208002d2efae6ba2be8eff453c5b7f9
  github:         Dinesh94Singh
  linkedin:       Dinesh Singh
  facebook:       Dinesh Singh

paginate:         5

# Custom vars
version:          2.1.0

plugins:
  - jekyll-paginate
  - jekyll-gist
